### PR TITLE
Add timeout in response

### PR DESCRIPTION
**Pull request by peppe-hmrc**

### CODE REVIEW

**Comment by peppe-hmrc** [comment]
this goes with https://github.com/hmrc/common-transit-convention/pull/36

**Comment by peppe-hmrc** [comment]
This has been already approved. Last commis is only merging conflicts

**Comment by peppe-hmrc** [comment]
> This is a weird decision and can't truly understand why you wanted to include the transit in the timeoutExtension response ...? Is it to refresh the page?

Hey Robert, I'm really sorry I missed your comment here. 
Yes I totally agree with you that is very very weird decision, and yes this is done mainly to make the FE able to refresh the page. Thus we don't have problem if we need to support the page without javascript.
I think this will no longer needed if we implement a page refresh guaranteeing that the user will receive the same MRN. I believe this will be possible once we fully integrate with Stride and we decide to implement such solution.

**Comment by robertbutacu** [comment]
But doesn't the frontend already have all the details for the current transit being processed? Can't that be reused somehow? Im currently working on the splunk events, and even though Andrei is sending the request to extend the timeout using JS, he's still able to send me the whole transit as a Form - although im sure he have it be in the body just the same way

**Comment by peppe-hmrc** [comment]
I'm not sure is possible to refresh the page and carry all the info to the next page. It would be better involving Andrei on this

**Pull request merged**
